version: '3.7'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
        MONGO_HOST: "mongodb"
        MONGO_PORT: "27017"
        MONGO_DATABASE: "books"
        MONGO_USERNAME: ""
        MONGO_PWD: ""
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "books"
